FROM zycgit/environment
MAINTAINER ZhaoYongChun "zyc@hasor.net"


# work
#VOLUME /work
ENV WORK_HOME /work

# git
#ADD . /usr/share/deployScript
#RUN ln -s /usr/share/deployScript /script \
#        && chown 755 /script/*.sh


#ENTRYPOINT [ "/script/init_gnupg.sh" , "userName" , "user@mail.cc" , "password" ]

#CMD ["~/script/pre_gpg.sh"]
#       && ln -s /usr/share/deployScript/init_gnupg.sh /etc/init.d/init_gnupg.sh